/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bandage: typeof import('./src/components/Bandage.vue')['default']
    IconDownload: typeof import('./src/components/icon/IconDownload.vue')['default']
    IconUpload: typeof import('./src/components/icon/IconUpload.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    ServerItem: typeof import('./src/components/ServerItem.vue')['default']
    StatusIndicator: typeof import('./src/components/StatusIndicator.vue')['default']
  }
}
